// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PluginRegistry.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(PluginDbContext))]
    partial class PluginDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("PluginRegistry.Plugins.PluginRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BundleUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plugins");

                    b.HasData(
                        new
                        {
                            Id = "sample-balance-widget",
                            BundleUrl = "http://localhost:4300/plugin.js",
                            Checksum = "sha256:8d696e29c65c4c5b9dd652cbf10ad3bc4a76690035c0aa0f25aa059b09623e6e",
                            Name = "Balance Widget",
                            Permissions = "auth.getCurrentUser",
                            Placements = "dashboard",
                            Status = 1,
                            TagName = "internal-balance-widget",
                            VendorId = "internal",
                            Version = "1.0.0"
                        });
                });

            modelBuilder.Entity("PluginRegistry.Plugins.TenantPlugin", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedRoles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "PluginId");

                    b.ToTable("TenantPlugins");

                    b.HasData(
                        new
                        {
                            TenantId = "ORG01",
                            PluginId = "sample-balance-widget",
                            AllowedRoles = "CUSTOMER,TELLER"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
